### ISSUE TITLE
EKF SLAM

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#13]
Convert example to use EKF function created by another team member, make measurement and motion models modular, improve gradient construction and resize map efficiently as new features are observed.  Extend example to different maps, and different sensor models.

**Comment by nanwei1** [comment]
Hello Prof. Waslander, could you be more specific about what you meant by "improve gradient construction?"

**Comment by stevenwaslander** [comment]
To use different measurement and motion models in the EKF, you need the linearized model, for which you have to define the gradient of the model equations.  A way to do this and use it in the EKF that is standard, so that every sensor would have a measurement model function, and a measurement gradient function, would be cool.
