### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#15]
Functionalize occupancy grid mapping with inverse measurement models.Test on multiple environments, and with different sensor options.  Use inverse measurement models for lidar, sonar in both windowed block update mode and bresenham ray trace mode.  Test on both small and large maps.

**Comment by icolwell** [comment]
Would it be worthwhile to delve into object oriented programming in MatLab? It could clean some things up nicely but I don't know how widely used MatLab OOP is, I wouldn't want to over complicate it. Your above comment specifically says "functionalize" so I'm guessing I should stay away from OOP.

**Comment by stevenwaslander** [comment]
Yes, definitely resist the urge to OOP in Matlab.  Functions only.

**Comment by alexsb92** [comment]
Just a small bug I noticed in the inversescannerbres.m file, when creating m, it should be 
`m = [list 0.4*ones(length(list(:,1)),1)];`
as with just list there it won't work as expected when only one point was found on the ray.
