### ISSUE TITLE
Trajectories

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#20]
Functionalize and allow any motion model to define motions.  Define a class of input functions that generate particular trajectories (swerves, nudges, lane changes, corners).

**Comment by yshiyi** [comment]
Dear, Prof.

I'd like to sign myself up for this issue.
What does the nudges motion look like?
Thank you, professor.

Shiyi

**Comment by stevenwaslander** [comment]
It looks like a small turn, so many nudges in a row would get you around a corner, and individual nudges would let you follow the road.

**Comment by yshiyi** [comment]
![nudges](https://cloud.githubusercontent.com/assets/17319992/13496430/288943e2-e11e-11e5-8557-d48246c4b67a.jpg)

Dear, Prof.
Is the attachment figure what individual nudges looks like?
Thank you.

**Comment by stevenwaslander** [comment]
That would be multiple nudges.  Think of it as a small heading change, in my slides, the function makes a star pattern based on how long the nudge (turn) maneuver is held for.  It would be neat to do an example with a few nudges to follow a curved portion of road way, and a swerve to miss a parked car.

**Comment by yshiyi** [comment]
Got your point, professor. Then what is the difference between swerves and lane change?
It seems like they both make the vehicle change lane to avoid frontal obstacle.
Thank you, professor.

**Comment by stevenwaslander** [comment]
Exactly right, a lane change would be a swerve that moves a full lane over.  Sometimes you only need to swerve a few feet to get around a blown tire or parked car.

**Comment by yshiyi** [comment]
Got it, professor. 
The final version of this program will allow user to select one trajectory from four predefined trajectories as spiral, nudges, swerves and corner. 
There is also an additional file which can be used to define any motions with any motion model. 
I hope this can meet the condition of this issue.
Thank you, professor.

**Comment by stevenwaslander** [comment]
Sounds promising, nice work.  Did you also make a nice example using these motions?

**Comment by yshiyi** [comment]
![corner](https://cloud.githubusercontent.com/assets/17319992/13517712/3f5aad10-e194-11e5-9b0c-ce59d32eef59.jpg)
![nudges](https://cloud.githubusercontent.com/assets/17319992/13517715/3f7c84d0-e194-11e5-9e56-41a7edf58ee2.jpg)
![spiral](https://cloud.githubusercontent.com/assets/17319992/13517714/3f7ab4c0-e194-11e5-945f-a7eee2eaa3cd.jpg)
![swerves](https://cloud.githubusercontent.com/assets/17319992/13517713/3f73bae4-e194-11e5-89d0-7c5da64094c9.jpg)

![command window](https://cloud.githubusercontent.com/assets/17319992/13517762/a395a082-e194-11e5-863a-6f2f088f4fdc.jpg)

The attachment figures are the plots of those motions and the command window.
You may see that after user choose the trajectory, user can give any initial condition to start the program.
In addition, if user defines a new motion model, user can also choose "5" at the beginning.
Thank you, professor.
