### ISSUE TITLE
Wavefront

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#29]
Convert wavefront to use standard environments (use maps or functions to be added to environments folder), make efficient if possible and test on small and large environments.  Create a function that computes the wavefront for any binary array (example exists in gallery_wavefront, one of the review exercises).

**Comment by StanJBrown** [comment]
Was I only supposed to update the functions in the planning folder? Or is there some code or examples else where that I should be also looking at/fixing?
