### ISSUE TITLE
Kalman filter

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#8]
The three kalman filter examples need to use a common kalman filter function, taking in the state space model, state, measurement etc.  Examples need to be easily selectable.

**Comment by rebellojason7** [comment]
Hello Professor Waslander, 
Could you elaborate on "Examples need to be easily selectable". I have modified the code in 2 ways. 1) Has 3 example files just like the original code and they call the common kalman filter function. 2) I have one file called 'test_examples' where you can modify the 'example' parameter to be assigned to 1,2 or 3. They also use the common kalman filter function.
