### ISSUE TITLE
Particle filter

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#9]
Needs to be functionalized, and made more efficient.  Multiple examples are needed. Must work for flyover example, and feature localization.

**Comment by chutsu** [comment]
Signing myself up for this one.

**Comment by chutsu** [comment]
I have a question, so in the old code there are quite a few examples, some of which I'm not sure whether I should refactor them?:
- `ellipse.m`
- `importance.m`
- `nonlinear.m`
- `nonlinearmapping.m`
- `normal.m`
- `reesampling.m`

Or should I just refactor exactly two examples,  flyover example and the feature localization example.

**Comment by stevenwaslander** [comment]
```
Woah, not sure what all those are, do they all work? You're welcome
to only focus on the EKF/UKFSlam example, the others may be junk
files or different examples.

Steve

On 2/29/2016 2:40 PM, Christopher Choi
  wrote:



  I have a question, so in the old code there are quite a few
    examples, some of which I'm not sure whether I should refactor
    them?:

    ellipse.m
    importance.m
    nonlinear.m
    nonlinearmapping.m
    normal.m
    reesampling.m

  Or should I just refactor exactly two examples, flyover example
    and the feature localization example.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by chutsu** [comment]
Haha, too late I already refactored them. The files are not as pointless as we first thought, they are actually the code that produces some of the plots in Estimation I and II slides. e.g. `resampling.m` corresponds to the **particle deprivation** problem, `nonlinear.m` plots the linear and nonlinear transform, how a nonlinear transform does not preserve a gaussian distribution, relevant slides 99 to 101 (kind of..) in Estimation I.

**Comment by chutsu** [comment]
Also do you mind if I just do the Particle Localization of the old `ME597-6-ParticleLocalization` code? I feel if I do the EKF/UKFSlam it goes beyond this issue's scope.

**Comment by stevenwaslander** [comment]
Sounds good.

**Comment by chutsu** [comment]
Done, please see PR #32
